### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by wergnbv** [k3b/CalendarIcsAdapter#15]
This doesn't work at all, when I try to open a .ics file with icsadapter 50% of the time my phone just freezes completely and I have to force it to shut off (do you guys support local calendars?), the other 50% only the first event is added and the rest in the .ics file is ignored.

**Comment by k3b** [comment]
thanks for feedback. your comment sound as if you try to import an ics file with many events which might run into out of memory situation.

the current implementation reads the complete ics-file and opens a prepopulated import-Activity for each event it finds in the file. if the file is big enought and there is not enought system memory your android will run out of memory.

i am usinng the adapter nearly every day with ics files wich contain only one event and i have no problems with my  old android 2.2. I have tested that it works with a 8-event file. 

I will update the documentation that the adapter can only handle a few events per ics.

Can you give me some details: which android version are you using, how moch ram and how many events per ics-file did you have?

**Comment by wergnbv** [comment]
Yes, I've been trying to import my entire summer school timetable lol, now I can see why this is an unreasonable demand.

I'm running Slimkat bacon weekly 8.14, which is based on Kitkat 4.4.4
3gbs of ram
Not sure if this is going to be useful anymore.

**Comment by k3b** [comment]
See also issue #10 https://github.com/k3b/CalendarIcsAdapter/issues/10  Import multiple entries. 

If it is ok for you i will close this issue as wont-t-fix

**Comment by wergnbv** [comment]
I've imported the ics through google, the file has 12 events, I can't see why that won't fit into 3gbs of ram?

**Comment by k3b** [comment]
added a code fix. now only one event is added at a time instead all togehter in parallel
