### ISSUE TITLE
Support different mimetypes

### ISSUE THREAD

**Issue by dicer** [k3b/CalendarIcsAdapter#18]
Looking at the ICS or ical attachments I get, I currently see the following mimetypes for these attachments:
text/calendar
application/ics

As far as I can tell this app does recognize the file ending only when I open an ics file with a filemanager. In k9mail it only recognizes text/calendar.

Would it be possible to also add application/ics to the handled mimetypes?

**Comment by k3b** [comment]
I was not aware that there is a mime-type application/ics

**Comment by dicer** [comment]
From what I can find on the internet, it seems Google is also sending them out with application/ics. Some software sends out calendar entries as multiple attachments. text/calendar AND application/ics. I think I can remember there being an issue somewhere where people also saw two attachments and only one worked. This might be the reason.

I did a very quick test and it seems just adding another data with mimetype to the AndroidManifest seems to solve it for me. Have not done many tests though.

**Comment by dicer** [comment]
Well, it certainly is not registered with IANA: https://www.iana.org/assignments/media-types/media-types.xhtml
So what to do? It's not official, but seems to be used

**Comment by k3b** [comment]
I will add it till end of july. do you have any idea how i can test it? do you know any free android app that sends " application/ics"

**Comment by dicer** [comment]
My usecase is the website meetup.com
They send you emails with this kind of mimetype after you join a meetup and a new event comes up. Haven't looked into any apps.

**Comment by ghost** [comment]
IANA recognizes the mime type now:
https://www.iana.org/assignments/media-types/media-types.xhtml#text

My Linux system (Fedora) has "text/calendar     ics ifb" in /etc/mime.types. Should "ifb" (Internet Free/Busy) be added as well?:
http://blogs.msdn.com/b/deva/archive/2009/01/06/tutorial-internet-free-busy-ifb-feature-ical-series-2.aspx

This wikipedia entry lists .ical, .ics, .ifb, and .icalendar as valid extensions:
https://en.wikipedia.org/wiki/ICalendar

**Comment by dicer** [comment]
Still don't see application/ics at IANA. 
text/calendar was always supported by this app.

I have been running the following patch since last year with success:
https://github.com/dicer/CalendarIcsAdapter/commit/b95d9db1a77cba0a03ea7bb3e1d54f35a51bf8d9

At least on CM11 this seems to work perfectly.

**Comment by ghost** [comment]
You're right. I misread. I thought you were talking text/calendar.

Is "ifb" handled as well?

**Comment by dicer** [comment]
From a filemanager: no. 
Only the following file endings are supported (currently):
.ics; .ical; .icalendar

Via intent it might, as long as the mimetype is correct. I usually open them via k9mail, so only the mimetype counts. So it should work from there.

I do see files though that are formatted in a way the used lib can't handle. That's another problem though.

**Comment by dicer** [comment]
Do you have an ifb file you could attach here? Then we could try if the lib for ical parsing supports it. Then again, what is the supposed outcome of a Free/Busy file? A new calendar entry? Sounds a bit weird.

**Comment by ghost** [comment]
I don't have an example of an ifb attachment. Your application came up as a possible solution for Etar's lack of direct ICS support: https://github.com/xsoh/Etar-Calendar/issues/31. 

"ifb" would modify an existing event, wouldn't it? I'll see if I can get an example from Outlook: I'll schedule a meeting on Outlook, add my GMail account as an invite, and see what shows in the attachment. I know I've accepted and declined meeting requests before, but it's been a while.

https://www.ietf.org/rfc/rfc2445.txt

"The file extension of "ifb" is to be used to designate a file
containing free or busy time information consistent with this MIME
content type."

Here's a VERY detailed example: http://www.kanzaki.com/docs/ical/vfreebusy.html

Another example: http://ilrt.org/discovery/2001/06/schemas/ical-full/old/examples/
(NOTE: the "full" examples appear to be there, the "skical" do not. I get a parsing error if I click the link; right-click and save allows local viewing).

**Comment by dicer** [comment]
As far as I understand ifb, it would just be a format where clients can look up the free/busy times of other people. So when you are planning a meeting with X people, you get each their ifb to see if they are free on that date or not. Haven't looked much into it though. If it is like I think, this would be out of scope I guess.

**Comment by ghost** [comment]
I believe you're right. My thought is ifb is "calendar-to-calendar", not "email-to-calendar", or something along those lines. It would imply access to another user's calendar. Thank you for looking at this.

**Comment by mathstuf** [comment]
I'm also seeing `application/ics` MIME types here. Even if IANA doesn't recognize it, it certainly is out in the wild.

**Comment by mathstuf** [comment]
And opening from an email client (K-9 here) fails since it has the MIME from the email, but saving it and opening from the file manager works since that goes by extension.

**Comment by dicer** [comment]
Added a pull request. Maybe we can get this merged and a new version out to fdroid?

**Comment by mathstuf** [comment]
Woo! Thanks.

**Comment by k3b** [comment]
i was not aware that my adapter is still in unse since modern android have a build in functionality for ics im and export. Is there any reason to use my adapter instead of google-s?

**Comment by mathstuf** [comment]
I don't have a handler for its files without this. On Android 6. But I also disable the now-crippled stock Calendar application and use Etar instead.

**Comment by ghost** [comment]
I'm running Android AOSP 6.0 with the AOSP Calendar (Etar is also based-on AOSP Calendar); I'm not seeing any built-in ics support.

**Comment by dicer** [comment]
I'm on CM13 (Android 6.0.1) and I do see the "Open with Calendar" intent
when clicking on an .ics file in the file manager. Good to know! Didn't
even realize

**Comment by k3b** [comment]
Thanks for the feedback.

The import code (or "Open with Calendar") of k3b/CalendarIcsAdapter is functional equivalent to  the code from danielegobbetti/ICSImport (because it was originally based on his code)

the ics-exportcode is useless:

i wrote CalendarIcsAdapter for my android-2.2 to hook beween calendar-list and calendar.edit so when opening the editor i got a chooser "edit-calendar-event" or "send-calendar-event-to". 

i intercepted 

```
            <action android:name="android.intent.action.EDIT" />
            <data android:scheme="content" />
            <data android:mimeType="vnd.android.cursor.item/event" />
```

which is called by old calendar-list to open calendar-edit  

the current google calendar is not interceptable any more so my calendar export code is useless nowadays. Is there any calendar app out that is capable to use the ics-export?

Do you see any reasons why is shout goon with k3b/CalendarIcsAdapter? Use danielegobbetti/ICSImport instead

**Comment by k3b** [comment]
changes are merged
